[en]
  languageName = "ğŸ‡ºğŸ‡¸ English"
  languageCode = "en-US"
  weight = 10
  [en.params]
    languageISO = "EN"



[es]
  languageName = "ğŸ‡ªğŸ‡¸ Spanish"
  languageCode = "es-ES"
  weight = 30
  [es.params]
    languageISO = "ES"
    description = "Una billetera de ahorros de bitcoin para toda la familia."

[fr]
  languageName = "ğŸ‡«ğŸ‡· FranÃ§ais"
  languageCode = "fr-FR"
  weight = 40
  [fr.params]
    languageISO = "FR"

[ko]
  languageName = "ğŸ‡°ğŸ‡· í•œêµ­ì–´"
  languageCode = "ko-KR"
  weight = 50
  [ko.params]
    languageISO = "KO"

[ru]
  languageName = "ğŸ‡·ğŸ‡º Ğ ÑƒÑÑĞºĞ¸Ğ¹"
  languageCode = "ru-RU"
  weight = 60
  [ru.params]
    languageISO = "RU"

[ca]
  languageName = "ğŸ‡ªğŸ‡¸ CatalÃ "
  languageCode = "ca-ES"
  weight = 70
  [ca.params]
    languageISO = "CA"

[ar]
  languageName = "ğŸ‡¦ğŸ‡ª Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©"
  languageCode = "ar-AE"
  weight = 80
  [ar.params]
    languageISO = "AR"

[th]
  languageName = "ğŸ‡¹ğŸ‡­ à¹„à¸—à¸¢"
  languageCode = "th-TH"
  weight = 90
  [th.params]
    languageISO = "TH"

[zh]
  languageName = "ğŸ‡¨ğŸ‡³ ç®€ä½“ä¸­æ–‡"
  languageCode = "zh-CN"
  weight = 100
  [zh.params]
    languageISO = "ZH"

[hi]
  languageName = "ğŸ‡®ğŸ‡³ à¤¹à¤¿à¤¨à¥à¤¦à¥€"
  languageCode = "hi-IN"
  weight = 110
  [hi.params]
    languageISO = "HI"

[it]
  languageName = "ğŸ‡®ğŸ‡¹ Italiano"
  languageCode = "it-IT"
  weight = 120
  [it.params]
    languageISO = "IT"

[de]
  languageName = "ğŸ‡©ğŸ‡ª Deutsch"
  languageCode = "de-DE"
  weight = 130
  [de.params]
    languageISO = "DE"

[my]
  languageName = "ğŸ‡²ğŸ‡² á€™á€¼á€”á€ºá€™á€¬"
  languageCode = "my-MM"
  weight = 140
  [my.params]
    languageISO = "MY"

[ja]
  languageName = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èª"
  languageCode = "ja-JP"
  weight = 150
  [ja.params]
    languageISO = "JA"

[fa]
  languageName = "ğŸ‡®ğŸ‡· ÙØ§Ø±Ø³ÛŒ"
  languageCode = "fa-IR"
  weight = 160
  [fa.params]
    languageISO = "FA"

[pt]
  languageName = "ğŸ‡µğŸ‡¹ PortuguÃªs (Portugal)"
  languageCode = "pt-PT"
  weight = 170
  [pt.params]
    languageISO = "PT"

[pl]
  languageName = "ğŸ‡µğŸ‡± Polski"
  languageCode = "pl-PL"
  weight = 180
  [pl.params]
    languageISO = "PL"



[id]
  languageName = "ğŸ‡®ğŸ‡© Indonesian"
  languageCode = "id-ID"
  weight = 190
  [id.params]
    languageISO = "ID"
    description = "Dompet tabungan bitcoin untuk seluruh keluarga."

[tr]
  languageName = "ğŸ‡¹ğŸ‡· Turkish"
  languageCode = "tr-TR"
  weight = 200
  [tr.params]
    languageISO = "TR"
    description = "TÃ¼m aile iÃ§in bir bitcoin tasarruf cÃ¼zdanÄ±."

[uk]
  languageName = "ğŸ‡ºğŸ‡¦ Ğ£ĞºÑ€Ğ°Ñ—Ğ½ÑÑŒĞºĞ°"
  languageCode = "uk-UA"
  weight = 210
  [uk.params]
    languageISO = "UK"
